### ISSUE TITLE
When region consists of n full lines, (n+1)th line moves as well

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [targzeta/move-lines#1]
To reproduce, select the first two lines in the following snippet:

```
FIRST
SECOND
third
fourth
```

That is, mark is at the beginning of the first line, point is at the beginning of the _third_ line.

Now press `M-<down>` once.

Observed result:

```
fourth
FIRST
SECOND
third
```

Expected result:

```
third
FIRST
SECOND
fourth
```

**Comment by targzeta** [comment]
It's not a bug, is a feature! move-lines moves all the lines from mark to point. If your point is on the third line, the third line it's part of the region!
