### ISSUE TITLE
Wide-characters in region move mark and point

### ISSUE THREAD

**Issue by jaredwindover** [targzeta/move-lines#3]
I've got tabs at the beginning of my lines, and the result is that the mark and point shift to the right after each movement. This is because (point) gives the number of characters into the document we are, but (current-column) gives the number of columns into the row we are, so if we're at the end of a document that consists of a single tab (and my tabs display as two columns), (point) will give us 1 but (current-column) will give us 2. This results in issues when the point and mark are restored. I've got my own version working by replacing the invocations of current-column with this:
```
(defun current-column-c ()
	(let ((col (point)))
		(save-excursion
			(beginning-of-line)
			(- col (point)))))
```

**Comment by targzeta** [comment]
[Tabs are evil](https://www.emacswiki.org/emacs/TabsAreEvil) ;-)!

Thank you very much Jared! I have completly rewritten the algorithm so that we don't rely on `current-column` function.
